name: Build on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@v3
        with:
          cmakeVersion: '3.24.1'  # Specify the CMake version you want to use

      - name: Configure with CMake
        run: cmake -B build

      - name: Build with CMake
        run: cmake --build build --config RelWithDebInfo

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Build
          path: build/RelWithDebInfo/  # Adjust if your output path is different
