name: Build on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install CMake
        run: |
          choco install cmake --install-args 'ADD_CMAKE_TO_PATH=System' --yes
        shell: powershell

      - name: Configure with CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Build
          path: build/Release/
      
      - name: Upload Nightly
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Nightly'
          prerelease: true
          body: |
            This is the latest build for commit ${{ github.sha }}
            This build may not be stable. might cause crashes
          files: build/Release/
